//! macOS sys/proc_info.h bindings generated by bindgen.
//!
//! This module provides FFI bindings for the proc_bsdshortinfo structure
//! and related constants from sys/proc_info.h.

#![expect(non_camel_case_types)]

include!(concat!(env!("OUT_DIR"), "/sys_proc_info.rs"));
